// COPIED from palm-ai-new--feat-m1-foundation/src/features/knowledge/rule-set-version.ts at app commit 38389f51b74d (2026-09-26).
// Do not edit by hand: change the app, then run `node scripts/sync-palm-lib.mjs` (ARCHITECTURE.md F7).
// @ts-nocheck
// Generated by `npm run rules:version` (tools/review/rule-set-version.mjs). Do not edit.
// sha-256 of the canonical active rule set — see rule-set-canonical.ts.
export const RULE_SET_VERSION = '73baeab538792c458a9a6905dfb7a02f023cd6c38f8ed9cc4a030f4a2274645b';
