import type { Locale } from '../../config/site';

/**
 * UI words of the guide template (the prose itself lives in the MDX files).
 * Kept out of the shared dictionaries so the guide template can grow without
 * touching them. The Hindi column waits for the owner or the Hindi reviewer
 * (CONTENT_GUIDE.md §10); no Hindi guide is built until then.
 */
const en = {
  writtenBy: 'Written by',
  reviewedBy: 'Reviewed by',
  lastReviewed: 'Last reviewed',
  authorPending: 'author page',
  onThisPage: 'On this page',
  quickFacts: 'Quick facts',
  figureLabel: 'Drawing',
  inlineCtaLive: (line: string) => `Find your ${line} on your own photo`,
  inlineCtaLiveAll: 'See your own lines traced on your photo',
  inlineCtaSoon: 'The free reading on this website opens soon. Until then, see how a reading looks in the sample.',
  inlineCtaSoonLink: 'See the sample reading',
  sourceLabel: 'Source',
  whatWeSee: 'What you see',
  whatTraditionSays: 'What the tradition says',
  whatItCantTell: 'What it can’t tell you',
  myth: 'Myth',
  reality: 'Reality',
  limitsTitle: 'What palmistry can’t tell you',
  limitsBody:
    'Palm lines can’t tell dates, how long you’ll live, your health, whether or when you’ll marry, how many children you’ll have, or how much money you’ll make. Palmistry is a tradition for reflection, not a science.',
  limitsLink: 'Is palmistry real?',
  careLine:
    'If worries about your health or your life feel heavy, you don’t have to carry them alone. In India, call Tele-MANAS on 14416 (free, 24×7). In the US, call or text 988.',
  photoTitle: 'Taking a photo to read your palm',
  photoTips: [
    'Use bright, even daylight, near a window. A single lamp throws shadows that look like extra lines.',
    'Hold your hand flat and open, with the whole palm and the wrist crease in the frame.',
    'Keep the phone straight above your palm and hold still, so the lines stay sharp.',
  ],
  photoCantShow:
    'A phone photo shows the main lines well, and their breaks, branches and forks. Islands, chains, crosses, stars and triangles are too small for most phone cameras, so an honest reading leaves them out.',
  photoCheckerLink: 'Check your photo with the palm photo checker',
  faqTitle: 'Questions people ask',
  sourcesTitle: 'Sources',
  // End matter on the 4 line guides carries the line name (SEMANTIC_SEO_PLAN.md §3.2, WEB-DEC-051).
  quickFactsOf: (name: string) => `${name} quick facts`,
  faqTitleOf: (name: string) => `${name}: questions people ask`,
  sourcesTitleOf: (name: string) => `Sources for this ${name.toLowerCase()} guide`,
  endTitleOf: (name: string) => `See your own ${name.toLowerCase()}`,
  relatedLinesTitle: 'Related palm lines',
  sourcesPolicy: 'How we choose sources',
  // The end block's link to /app/ (§4.5 #4): two registered anchors, alternated by page.
  appBefore: 'Or see what the',
  appAnchors: ['PalmSays palm reading app', 'palm reading app for Android'],
  appAfter: 'reads before you install it.',
  sourcesNote:
    'Meanings on this page are written in our own words from these books. Books whose rights are unclear are used for facts only, never quoted.',
  factsOnly: 'facts only',
  inFrench: 'in French',
  inHindi: 'in Hindi',
  stepOf: (n: number) => `Step ${n} of 7`,
  previousStep: 'Previous step',
  nextStep: 'Next step',
  allSteps: 'All 7 steps: how to read palm lines',
  endTitleLive: 'See your own lines',
  endBodyLive: 'Upload one photo of your palm. We trace your lines and show what palmistry says about each one.',
  endButtonLive: 'Read my palm free',
  endTitleSoon: 'See your own lines',
  endBodySoon:
    'The free reading on this website opens soon. Until then, see how a reading looks in the sample, or read your palm today in our Android app.',
  endButtonSoon: 'See a sample reading',
  relatedTitle: 'Related guides',
  toolCardAction: (name: string) => `Try the ${name.toLowerCase()}`,
  // Guide template v3: the "Find your line" module, Step n of 4, cards, end block.
  findTitle: (line: string) => `Find your ${line}`,
  findTitleAll: 'Find your 4 main lines',
  lookHere: 'Look here',
  zoneName: { heart: 'Heart line', head: 'Head line', life: 'Life line', fate: 'Fate line', marriage: 'Marriage lines', simian: 'Top two lines' },
  photoGuide: 'A real palm photo. The shaded area shows where to look. It is a guide, not a traced line.',
  photoScan: 'A real palm photo. The shaded area is where our scanner found this line on this photo.',
  photoPins: 'A real palm photo. Each dot marks where a line usually runs. They are guides, not traced lines.',
  photoCredit: 'Photo',
  photoOn: (author: string, where: string) => `${author} on ${where}`,
  altGuide: (names: string) => `The area where the ${names.toLowerCase()} usually runs is shaded.`,
  altScan: (names: string) => `The area where the scanner found the ${names.toLowerCase()} is shaded.`,
  stepsTitle: 'Check your own hand',
  scanCta: 'Scan my palm to see mine',
  scanSoon: 'The scan on this website opens soon. Until then, our Android app can read your palm.',
  toolLink: (name: string) => `Or pick your shape in the ${name.toLowerCase()}`,
  seeCard: 'See this type',
  seeGuide: 'Open the guide',
  seeSection: 'Read more below',
  stepOf4: (n: number) => `Step ${n} of 4`,
  linesNav: 'The 4 main lines',
  lineShort: { heart: 'Heart line', head: 'Head line', life: 'Life line', fate: 'Fate line' },
  nextLine: (n: number) => `Next: step ${n} of 4`,
  startLines: 'Start the 4 main lines: step 1 of 4',
  allFour: 'You have seen all 4 main lines',
  allFourBody: 'The chart of every line on the palm shows the smaller ones too.',
  doYouHave: 'Do you have this?',
  booksSay: 'What the books say',
  sourcesSummary: (n: number) => `Sources (${n} ${n === 1 ? 'book or study' : 'books and studies'})`,
  sourcesSummaryOf: (name: string, n: number) => `Sources for this ${name.toLowerCase()} guide (${n} ${n === 1 ? 'book or study' : 'books and studies'})`,
  tipChips: ['Open palm', 'Good light', 'Whole hand in the frame'],
  tipCheckLink: 'Check your photo first',
  photoShort: 'A phone photo shows the main lines and their breaks, forks and branches. Tiny marks such as stars and crosses are too small, so an honest reading leaves them out.',
  // Guide template v4, "teach by seeing" (WEB-DEC-047): the traced hero and the teaching blocks.
  teach: {
    // The HD guide palm is a licensed real photo (Pexels 8058729, Hanna Pad; 2026-10-02, design-v4/photo-credits.json), credited where it shows; its lines are the real scanner's.
    heroAlt: (names: string) => `A real photo of an open right palm, fingers spread. The real PalmSays scanner traced these lines on it: ${names}.`,
    heroCaption: 'A real palm photo (Hanna Pad, Pexels), traced by the real PalmSays scanner. Your reading is made from your own photo.',
    // The owner's own left palm (find.photo: left-palm, WEB-DEC-048). Caption = DESIGN_SYSTEM.md §9 label, word for word.
    leftPalmAlt: (lines: readonly string[]) =>
      `A real open left palm, photographed indoors, with the ${lines.map((l) => l.toLowerCase()).join(', ').replace(/, ([^,]*)$/, ' and $1')} lines traced by PalmSays.`,
    leftPalmCaption: 'A real photo, traced by PalmSays. Your reading is made from your own photo.',
    showLine: 'Show one line',
    allLines: 'All',
    notClear: 'not clearly seen in this photo',
    playAgain: 'Play again',
    fingers: ['Thumb', 'Index', 'Middle', 'Ring', 'Little'],
    drawing: 'Drawing',
    aiImage: 'AI image',
    wordsCredit: 'The pictures are AI-made 3D images.',
    wordsTitle: 'Palmistry words to know',
    words: [
      { key: 'line', term: 'Line', hi: 'रेखा', hiLatin: 'rekha', text: 'A long crease across the palm. Palmistry reads four main ones.' },
      { key: 'crease', term: 'Crease', hi: 'सिलवट', hiLatin: 'silvat', text: 'A fold in the skin. The short ones where the fingers join the palm are finger creases.' },
      { key: 'mount', term: 'Mount', hi: 'पर्वत', hiLatin: 'parvat', text: 'A soft, raised pad of the palm, such as the ball of the thumb.' },
      { key: 'fork', term: 'Fork', hi: 'दो मुखी रेखा', hiLatin: 'do mukhi rekha', text: 'A line that splits in two at one end.' },
      { key: 'break', term: 'Break', hi: 'टूट', hiLatin: 'toot', text: 'A gap where a line stops and then starts again.' },
      { key: 'hand', term: 'Writing hand', hi: 'लिखने वाला हाथ', hiLatin: 'likhne wala haath', text: 'The hand you write with. Tradition reads it as the life you are making.' },
    ],
    flowTitle: 'How a reading works',
    flow: [
      { title: 'Look', text: 'at the lines, the mounts and the shape of the hand.' },
      { title: 'Learn', text: 'what the old books say about each one.' },
      { title: 'Ask yourself', text: '“Does this fit me?”' },
    ],
    stepMapTitle: 'The 7 steps at a glance',
    doLabel: 'Do',
    dontLabel: 'Don’t',
    photoDo: { alt: 'An open palm held flat in soft, even light, the whole hand close to the camera.', text: 'Open palm, daylight, close up.' },
    photoDonts: [
      { key: 'dark', alt: 'A hand held up in a dark room, mostly in shadow.', text: 'Too dark. Use daylight.' },
      { key: 'fist', alt: 'A closed fist.', text: 'A closed hand. Open it flat.' },
      { key: 'far', alt: 'A person far down a hallway holding up one hand, too small to see its lines.', text: 'Too far. Fill the frame.' },
      { key: 'back', alt: 'The back of a hand, fingers spread.', text: 'The back of the hand. Show the palm.' },
    ],
    photoCaption: 'The good photo is real (Hanna Pad, Pexels); the other example photos are AI-made. In a dark photo, shadows can look like extra lines or breaks.',
    hands: {
      writing: 'Your writing hand',
      writingText: 'the life you are making',
      other: 'Your other hand',
      otherText: 'what you started with',
      writingAlt: 'A hand writing on paper with a pen.',
      otherAlt: 'The other hand, resting open, palm up.',
      caption: 'Tradition reads your two hands differently, so look at both.',
    },
    shapesCaption: 'AI-made 3D pictures of the seven hand types in Cheiro’s Palmistry for All (1916). Not real people’s hands.',
    shapes: {
      elementary: { name: 'Elementary', alt: 'A short, thick palm with short fingers' },
      square: { name: 'Square', alt: 'A square palm with square-cut fingertips' },
      spatulate: { name: 'Spatulate', alt: 'Fingertips that widen at the ends' },
      philosophic: { name: 'Philosophic', alt: 'A long hand with knotty finger joints' },
      conic: { name: 'Conic', alt: 'A graceful hand with rounded, tapering fingers' },
      psychic: { name: 'Psychic', alt: 'A long, narrow hand with slender, pointed fingers' },
      mixed: { name: 'Mixed', alt: 'Each finger a different shape' },
    },
    readFor: 'Read for',
    readForLine: {
      heart: 'how you feel and show affection.',
      head: 'how you think and decide.',
      life: 'energy and how you meet change. Never for how long you live.',
      fate: 'direction and work. Many palms show it faintly, or not at all.',
    },
    lessonAlt: {
      heart: 'Close-up of the real palm. The scanner’s heart line runs from the little-finger edge up towards the gap between the index and middle fingers.',
      head: 'Close-up of the real palm. The scanner’s head line starts between the thumb and index finger and slopes across the middle of the palm.',
      life: 'Close-up of the real palm. The scanner’s life line starts between the thumb and index finger and curves around the ball of the thumb.',
      fate: 'Close-up of the real palm. The scanner’s fate line runs straight up the middle of the palm towards the middle finger.',
    },
    lessonCaption: (line: string) => `The photo: the ${line} on the same real palm, traced by the scanner. The drawings: three forms the books describe, not real palms.`,
    formsTitle: 'Three forms to look for',
    openGuide: (line: string) => `${line.charAt(0).toUpperCase()}${line.slice(1)} meaning`,
    questionsTitle: '4 lines, 4 questions',
    questions: {
      heart: 'How do I feel, and how do I show it?',
      head: 'How do I think and decide?',
      life: 'How do I use my energy and meet change?',
      fate: 'Which direction is my work taking?',
    },
    mountsAlt: 'The real palm with eight numbered areas: four under the fingers, one near the thumb inside the start of the life line, the ball of the thumb, and two on the outer edge above the wrist.',
    mountsCaption: 'Mount areas placed from the scanner’s hand points (knuckles, thumb and wrist), where the books put them. They are areas to press gently, not lines.',
    mounts: {
      jupiter: { name: 'Guru', hi: 'गुरु', planet: 'Jupiter', where: 'under the index finger' },
      saturn: { name: 'Shani', hi: 'शनि', planet: 'Saturn', where: 'under the middle finger' },
      sun: { name: 'Surya', hi: 'सूर्य', planet: 'Sun', where: 'under the ring finger' },
      mercury: { name: 'Budh', hi: 'बुध', planet: 'Mercury', where: 'under the little finger' },
      venus: { name: 'Shukra', hi: 'शुक्र', planet: 'Venus', where: 'the ball of the thumb' },
      moon: { name: 'Chandra', hi: 'चंद्र', planet: 'Moon', where: 'outer edge, above the wrist' },
      marsInner: { name: 'Mangal', hi: 'मंगल', planet: 'Mars', where: 'near the thumb' },
      marsOuter: { name: 'Mangal', hi: 'मंगल', planet: 'Mars', where: 'outer edge' },
    },
    notThis: 'Not this',
    this: 'This',
    mistakes: {
      crease: {
        not: 'The short creases where the fingers join the palm are finger creases.',
        notAlt: 'Close-up of the finger bases on the real palm, with the finger creases marked as an area.',
        yes: 'The heart line is the first long line below them.',
        yesAlt: 'The same close-up with the scanner’s heart line traced below the finger creases.',
      },
      start: {
        not: 'A line that starts near the thumb is the head line.',
        notAlt: 'The real palm with the scanner’s head line traced and its start near the thumb marked.',
        yes: 'The heart line starts at the little-finger edge.',
        yesAlt: 'The real palm with the scanner’s heart line traced and its start at the little-finger edge marked.',
      },
      shadow: {
        not: 'A dark photo. Shadows can look like breaks.',
        notAlt: 'A hand photographed in a dark room, mostly in shadow.',
        yes: 'Even daylight. The life line shows as one line.',
        yesAlt: 'The real palm in daylight with the scanner’s life line traced as one unbroken line.',
      },
    },
    right: 'Yes, that’s right.',
    wrong: 'Not quite.',
    quizCropAlt: 'Close-up of the real palm with one of the scanner’s lines traced in gold.',
    quiz: [
      {
        q: 'Which line is traced in gold on this photo?',
        crop: 'life',
        options: [
          { text: 'Heart line', ok: false, fb: 'The heart line is the top one, just under the fingers.' },
          { text: 'Head line', ok: false, fb: 'Close. The head line starts at the same spot, then runs across the palm.' },
          { text: 'Life line', ok: true, fb: 'It curves around the ball of the thumb towards the wrist.' },
        ],
      },
      {
        q: 'Where does the heart line start?',
        crop: null,
        options: [
          { text: 'At the little-finger edge of the palm', ok: true, fb: 'It runs from there towards the index or middle finger.' },
          { text: 'Between the thumb and the index finger', ok: false, fb: 'That is where the head and life lines start.' },
          { text: 'At the wrist', ok: false, fb: 'A fate line can start at the wrist. The heart line starts at the little-finger edge.' },
        ],
      },
      {
        q: 'What does the length of your life line tell you about how long you will live?',
        crop: null,
        options: [
          { text: 'A short line means a short life', ok: false, fb: 'No. Length is not read as lifespan, and a photo can make a line look shorter than it is.' },
          { text: 'Nothing: length is not read as lifespan', ok: true, fb: 'The books read the life line for energy and how you meet change.' },
          { text: 'The year a big change will come', ok: false, fb: 'No line gives a date. Palmistry describes tendencies.' },
        ],
      },
    ] as { q: string; crop: 'heart' | 'head' | 'life' | 'fate' | null; options: { text: string; ok: boolean; fb: string }[] }[],
    quizMore: 'More practice: the palm reading quiz',
    // The 4 line guides (guide v4 rollout, 2026-09-28): the hero with one line in focus, "Where is it?"
    // in 3 looks, the 4 questions, heart or head, and each page's own check.
    focusAlt: {
      heart:
        'A real photo of an open right palm, fingers spread. The real PalmSays scanner traced its lines; the heart line stands out, running from the little-finger edge towards the gap between the index and middle fingers. Dotted finger guides run down from each finger.',
      head: 'A real photo of an open right palm, fingers spread. The real PalmSays scanner traced its lines; the head line stands out, starting between the thumb and index finger and sloping across the middle of the palm. Dotted finger guides run down from each finger.',
      life: 'A real photo of an open right palm, fingers spread. The real PalmSays scanner traced its lines; the life line stands out, starting between the thumb and index finger and curving around the ball of the thumb. Dotted finger guides run down from each finger.',
      fate: 'A real photo of an open right palm, fingers spread. The real PalmSays scanner traced its lines; the fate line stands out, running up the middle of the palm towards the middle finger. Dotted finger guides run down from each finger.',
    },
    focusNote: (line: string) => `Dotted lines are finger guides, not palm lines. The solid dot marks where the ${line} starts, the ring where it ends.`,
    start: 'Start',
    end: 'End',
    skipThese: 'Skip these',
    looksTitle: 'Where is it? Three looks',
    looks: {
      heart: ['Name your fingers.', 'Skip the short creases where the fingers join the palm.', 'The first long line below them, from the little-finger edge.'],
      head: ['Name your fingers.', 'Skip the finger creases. The heart line is the first long line below them.', 'Just below the heart line, from between the thumb and index finger.'],
      life: ['Name your fingers, and find the ball of your thumb.', 'Skip the finger creases at the top of the palm.', 'The line that curves around the ball of the thumb.'],
      fate: ['Name your fingers, and find the middle one.', 'Skip the finger creases at the top of the palm.', 'The line up the middle, from the wrist end towards the middle finger.'],
    },
    looksAlt: {
      hand: 'The real palm photo, the whole hand, with each finger named from the scanner’s hand points.',
      creases: 'Close-up of the finger bases on the same photo, with the finger creases marked as an area to skip.',
      line: (line: string) => `Close-up of the ${line} on the same photo, traced by the real scanner, with a dot where it starts and a ring where it ends.`,
    },
    looksCaption: 'One real photo (Hanna Pad, Pexels), three looks. Finger names come from the scanner’s hand points, the creases are marked as an area, and the line is the scanner’s own.',
    anatomyTitle: 'Read any line with 4 questions',
    anatomy: [
      // `h` = the H3 over that group of type cards on each line guide ({line} = "heart line" …; heading spec, WEB-DEC-051).
      { key: 'ends', img: 'word-end', q: 'Where does it start and end?', h: 'Where does your {line} start and end?' },
      { key: 'length', img: 'word-line', q: 'How long is it?', h: 'How long is your {line}?' },
      { key: 'clear', img: 'word-clear', q: 'How clear is it?', h: 'How clear is your {line}?' },
      { key: 'marks', img: 'word-fork', q: 'Any breaks, forks or branches?', h: 'Does your {line} break, fork or branch?' },
    ],
    anatomyHint: {
      heart: ['Under which finger does it stop?', 'Right across the palm, or stopping early?', 'Deep and even, faint, or like a row of links?', 'A fork, a gap, or small branches rising?'],
      head: [
        'Joined to the life line at the start? Straight or sloping at the end?',
        'Nearly to the outer edge, or stopping mid-palm?',
        'Deep and even, faint, or like a row of links?',
        'A fork at the end, or a gap?',
      ],
      life: [
        'Starting high? Swinging wide, or close to the thumb?',
        'All the way round to the wrist, or stopping partway? Never read as years.',
        'Deep and even, faint, or like a row of links?',
        'A gap, a second line inside it, or a fork near the wrist?',
      ],
      fate: [
        'From the wrist, the life line, the outer palm or mid-palm? Which finger does it reach?',
        'Short, in pieces or missing: all common.',
        'Faint, or deep and heavily marked?',
        'A gap, or two lines side by side?',
      ],
    },
    anatomyCaption: 'AI-made 3D pictures. The glow shows the idea; it is not a reading.',
    sideBySide: 'Side by side, at one scale',
    drawingsCaption: 'Drawings of the forms the books describe, not real palms.',
    flowChoice: {
      title: 'Heart or head line?',
      q: 'Follow the line back to where it starts.',
      heart: { where: 'At the little-finger edge', is: 'It is the heart line.', alt: 'Close-up of the palm photo: the scanner’s heart line, with a dot where it starts at the little-finger edge.' },
      head: { where: 'Between the thumb and index finger', is: 'It is the head line.', alt: 'Close-up of the palm photo: the scanner’s head line, with a dot where it starts between the thumb and index finger.' },
      one: 'Only one line across the top half of your palm?',
      oneLink: 'When the heart and head lines join',
      oneHref: '#when-the-heart-and-head-lines-join',
      caption: 'The same real palm photo (Hanna Pad, Pexels); the lines and dots are the scanner’s own.',
    },
    flowChoiceLF: {
      title: 'Life or fate line?',
      q: 'Look at the way the line runs.',
      life: { where: 'It curves around the ball of the thumb', is: 'It is the life line.', alt: 'Close-up of the palm photo: the scanner’s life line curving around the ball of the thumb, with a dot where it starts.' },
      fate: { where: 'It runs straight up the middle', is: 'It is the fate line.', alt: 'Close-up of the palm photo: the scanner’s fate line running up the middle of the palm, with a dot where it starts.' },
      one: 'A line that leaves the life line and runs up the palm is read as a fate line.',
      oneLink: 'Life line vs fate line',
      oneHref: '/life-line/#life-line-vs-fate-line',
      caption: 'The same real palm photo (Hanna Pad, Pexels); the lines and dots are the scanner’s own.',
    },
    heartEnds: {
      a: 'Little-finger end',
      b: 'Finger end',
      alt: 'Close-up of the palm photo: the scanner’s heart line, with a dot at its little-finger end and a ring at its other end, towards the index and middle fingers.',
      caption: 'The two ends of the heart line on the same real photo (Hanna Pad, Pexels), as the scanner traced it. Some books read from the little-finger end, others from the finger end.',
    },
    lineQuiz: {
      heart: [
        {
          q: 'Is the line traced in gold the heart line?',
          crop: 'head',
          options: [
            { text: 'Yes, it is the heart line', ok: false, fb: 'It starts between the thumb and index finger and runs lower: that is the head line.' },
            { text: 'No, it is the head line', ok: true, fb: 'The heart line sits higher and starts at the little-finger edge.' },
            { text: 'It is a finger crease', ok: false, fb: 'Finger creases are the short ones where the fingers join the palm.' },
          ],
        },
        {
          q: 'What do the books read in a heart line that ends under the index finger?',
          crop: null,
          options: [
            { text: 'Loyal, steady affection held to high ideals', ok: true, fb: 'Cheiro and Markun both read it that way: a style of affection, not an event.' },
            { text: 'The year you will marry', ok: false, fb: 'No line gives a date, or says whether you will marry.' },
            { text: 'A weak heart', ok: false, fb: 'Palm lines are not a health test. For your heart, see a doctor.' },
          ],
        },
        {
          q: 'Your heart line looks broken in a photo. What should you check first?',
          crop: null,
          options: [
            { text: 'The light: even daylight, hand flat', ok: true, fb: 'A crease or a shadow can make a line look broken in a photo.' },
            { text: 'Nothing: it means heartbreak', ok: false, fb: 'The books read a break as attachment that is slower to settle, never as heartbreak.' },
            { text: 'Your other lines', ok: false, fb: 'Check this line again in good light first. Shadows fool the eye.' },
          ],
        },
      ],
      head: [
        {
          q: 'Is the line traced in gold the head line?',
          crop: 'heart',
          options: [
            { text: 'No, it is the heart line', ok: true, fb: 'It starts at the little-finger edge, just under the fingers.' },
            { text: 'Yes, it is the head line', ok: false, fb: 'The head line sits lower and starts between the thumb and index finger.' },
            { text: 'It is the life line', ok: false, fb: 'The life line curves around the ball of the thumb.' },
          ],
        },
        {
          q: 'What do the books read in a short head line?',
          crop: null,
          options: [
            { text: 'A practical, focused mind', ok: true, fb: 'A hands-on mind that focuses closely on one thing.' },
            { text: 'Low intelligence', ok: false, fb: 'No. Length is never read as intelligence.' },
            { text: 'Poor exam results', ok: false, fb: 'No line can predict exams or degrees.' },
          ],
        },
        {
          q: 'What is the writer’s fork?',
          crop: null,
          options: [
            { text: 'A head line that splits in two near its end', ok: true, fb: 'Read as practical and imaginative thinking at once.' },
            { text: 'Two separate head lines', ok: false, fb: 'That is a double head line, which is different from a fork.' },
            { text: 'A gap in the head line', ok: false, fb: 'A gap is a break. A fork is a split near the end.' },
          ],
        },
      ],
      life: [
        {
          q: 'Is the line traced in gold the life line?',
          crop: 'fate',
          options: [
            { text: 'No, it is the fate line', ok: true, fb: 'It runs straight up the middle. The life line curves around the thumb.' },
            { text: 'Yes, it is the life line', ok: false, fb: 'The life line curves around the ball of the thumb towards the wrist.' },
            { text: 'It is the head line', ok: false, fb: 'The head line runs across the palm, not up it.' },
          ],
        },
        {
          q: 'Your life line looks short. What does that tell you about how long you will live?',
          crop: null,
          options: [
            { text: 'A short life', ok: false, fb: 'No. Length is never read as lifespan, and a photo can crop the line.' },
            { text: 'Nothing: length is not read as lifespan', ok: true, fb: 'The books read this line for energy and how you meet change.' },
            { text: 'An illness to come', ok: false, fb: 'Palm lines are not a health test. For health, talk to a doctor.' },
          ],
        },
        {
          q: 'What is a double life line?',
          crop: null,
          options: [
            { text: 'A second line just inside the life line', ok: true, fb: 'Cheiro calls it the inner life line and reads it as backing up the life line.' },
            { text: 'A sign of two lives', ok: false, fb: 'No. It is read as extra support for the life line, nothing more.' },
            { text: 'Another name for the fate line', ok: false, fb: 'The fate line runs up the middle of the palm.' },
          ],
        },
      ],
      fate: [
        {
          q: 'Which line is traced in gold on this photo?',
          crop: 'fate',
          options: [
            { text: 'Life line', ok: false, fb: 'The life line curves around the ball of the thumb.' },
            { text: 'Fate line', ok: true, fb: 'It runs up the middle of the palm towards the middle finger.' },
            { text: 'Head line', ok: false, fb: 'The head line runs across the palm, not up it.' },
          ],
        },
        {
          q: 'You can’t find a fate line. What does that mean?',
          crop: null,
          options: [
            { text: 'No luck, or no career', ok: false, fb: 'No. It is common, and it is not read as bad luck.' },
            { text: 'A path that isn’t fixed in advance', ok: true, fb: 'That is the gentler reading the books keep. Many palms show no fate line.' },
            { text: 'You will lose your job', ok: false, fb: 'No line predicts a job or an income.' },
          ],
        },
        {
          q: 'What do the books read in a broken fate line?',
          crop: null,
          options: [
            { text: 'A change of direction in work', ok: true, fb: 'A real change of job or surroundings, rather than one straight road.' },
            { text: 'Failure', ok: false, fb: 'The books disagree on how a change turns out, so no outcome is read.' },
            { text: 'The year you will change jobs', ok: false, fb: 'No line gives a date.' },
          ],
        },
      ],
    } as Record<'heart' | 'head' | 'life' | 'fate', { q: string; crop: 'heart' | 'head' | 'life' | 'fate' | null; options: { text: string; ok: boolean; fb: string }[] }[]>,
  },
};

type GuideStrings = typeof en;

const hi: GuideStrings = {
  writtenBy: 'लेखक',
  reviewedBy: 'जाँच',
  lastReviewed: 'आख़िरी बार जाँचा गया',
  authorPending: 'लेखक पेज',
  onThisPage: 'इस पेज पर',
  quickFacts: 'मुख्य बातें',
  figureLabel: 'चित्र',
  inlineCtaLive: (line: string) => `अपनी फ़ोटो पर अपनी ${line} देखें`,
  inlineCtaLiveAll: 'अपनी फ़ोटो पर अपनी रेखाएं देखें',
  inlineCtaSoon: 'इस वेबसाइट पर मुफ़्त रीडिंग जल्द खुलेगी। तब तक सैंपल में देखें कि रीडिंग कैसी दिखती है।',
  inlineCtaSoonLink: 'सैंपल रीडिंग देखें',
  sourceLabel: 'स्रोत',
  whatWeSee: 'जो दिखता है',
  whatTraditionSays: 'परंपरा क्या कहती है',
  whatItCantTell: 'यह क्या नहीं बता सकती',
  myth: 'भ्रम',
  reality: 'सच',
  limitsTitle: 'हस्तरेखा क्या नहीं बता सकती',
  limitsBody:
    'हाथ की रेखाएं कोई तारीख़, आपकी उम्र, आपकी सेहत, शादी कब होगी, कितने बच्चे होंगे या कितना पैसा आएगा, ये बातें नहीं बता सकतीं। हस्तरेखा खुद को समझने की एक परंपरा है, विज्ञान नहीं।',
  limitsLink: 'क्या हस्तरेखा सच है?',
  careLine: 'अगर सेहत या ज़िंदगी की चिंता भारी लग रही है, तो आज ही किसी से बात करें। भारत में: Tele-MANAS 14416 (मुफ़्त, 24×7)।',
  photoTitle: 'हथेली की फ़ोटो कैसे लें',
  photoTips: [
    'दिन की अच्छी, बराबर रोशनी में, खिड़की के पास फ़ोटो लें। एक लैंप की परछाईं अतिरिक्त रेखा जैसी दिखती है।',
    'हाथ सीधा और खुला रखें, ताकि पूरी हथेली और कलाई की रेखा फ़ोटो में आए।',
    'फ़ोन को हथेली के ठीक ऊपर सीधा रखें और हिलाएं नहीं, ताकि रेखाएं साफ़ आएं।',
  ],
  photoCantShow:
    'फ़ोन की फ़ोटो में मुख्य रेखाएं, उनकी टूट, शाखाएं और दो मुखी सिरे अच्छे से दिखते हैं। द्वीप, जंजीर, क्रॉस, तारे और त्रिभुज ज़्यादातर फ़ोन कैमरे में साफ़ नहीं आते, इसलिए ईमानदार रीडिंग इन्हें छोड़ देती है।',
  photoCheckerLink: 'पाम फ़ोटो चेकर से अपनी फ़ोटो जाँचें',
  faqTitle: 'लोग क्या पूछते हैं',
  sourcesTitle: 'स्रोत',
  // Not reviewed yet: no Hindi guide is built.
  quickFactsOf: (name: string) => `${name}: मुख्य बातें`,
  faqTitleOf: (name: string) => `${name}: लोग क्या पूछते हैं`,
  sourcesTitleOf: (name: string) => `${name} गाइड के स्रोत`,
  endTitleOf: (name: string) => `अपनी ${name} देखें`,
  relatedLinesTitle: 'हाथ की और रेखाएं',
  sourcesPolicy: 'हम स्रोत कैसे चुनते हैं',
  appBefore: 'या इंस्टॉल करने से पहले देखें कि',
  appAnchors: ['PalmSays हस्तरेखा ऐप', 'Android का हस्तरेखा ऐप'],
  appAfter: 'क्या पढ़ता है।',
  sourcesNote:
    'इस पेज के अर्थ इन किताबों से हमारे अपने शब्दों में लिखे गए हैं। जिन किताबों के अधिकार साफ़ नहीं हैं, उनसे सिर्फ़ तथ्य लिए गए हैं, उद्धरण नहीं।',
  factsOnly: 'सिर्फ़ तथ्य',
  inFrench: 'फ़्रेंच में',
  inHindi: 'हिंदी में',
  stepOf: (n: number) => `7 में से कदम ${n}`,
  previousStep: 'पिछला कदम',
  nextStep: 'अगला कदम',
  allSteps: 'सभी 7 कदम: हाथ की रेखा कैसे देखें',
  endTitleLive: 'अपनी रेखाएं देखें',
  endBodyLive: 'अपनी हथेली की एक फ़ोटो डालें। हम आपकी रेखाएं बनाते हैं और बताते हैं कि हस्तरेखा हर रेखा के बारे में क्या कहती है।',
  endButtonLive: 'मेरी हथेली मुफ़्त पढ़ें',
  endTitleSoon: 'अपनी रेखाएं देखें',
  endBodySoon:
    'इस वेबसाइट पर मुफ़्त रीडिंग जल्द खुलेगी। तब तक सैंपल में देखें कि रीडिंग कैसी दिखती है, या आज ही हमारे Android ऐप में अपनी हथेली पढ़ें।',
  endButtonSoon: 'सैंपल रीडिंग देखें',
  relatedTitle: 'और गाइड',
  toolCardAction: (name: string) => `${name} आज़माएं`,
  // Not reviewed yet: no Hindi guide is built until the owner or the Hindi reviewer reads it.
  findTitle: (line: string) => `अपनी ${line} ढूंढें`,
  findTitleAll: 'अपनी 4 मुख्य रेखाएं ढूंढें',
  lookHere: 'यहां देखें',
  zoneName: { heart: 'हृदय रेखा', head: 'मस्तिष्क रेखा', life: 'जीवन रेखा', fate: 'भाग्य रेखा', marriage: 'विवाह रेखाएं', simian: 'ऊपर की दो रेखाएं' },
  photoGuide: 'असली हथेली की फ़ोटो। रंगा हुआ हिस्सा बताता है कि कहां देखें। यह एक अंदाज़ा है, बनाई गई रेखा नहीं।',
  photoScan: 'असली हथेली की फ़ोटो। रंगा हुआ हिस्सा वह जगह है जहां हमारे स्कैनर को इस फ़ोटो पर यह रेखा मिली।',
  photoPins: 'असली हथेली की फ़ोटो। हर बिंदु बताता है कि रेखा आमतौर पर कहां होती है। ये अंदाज़े हैं, बनाई गई रेखाएं नहीं।',
  photoCredit: 'फ़ोटो',
  photoOn: (author: string, where: string) => `${author}, ${where}`,
  altGuide: (names: string) => `${names}: जहां यह आमतौर पर होती है, वह हिस्सा रंगा है।`,
  altScan: (names: string) => `${names}: जहां स्कैनर को यह मिली, वह हिस्सा रंगा है।`,
  stepsTitle: 'अपना हाथ देखें',
  scanCta: 'मेरी हथेली स्कैन करें',
  scanSoon: 'इस वेबसाइट पर स्कैन जल्द खुलेगा। तब तक हमारा Android ऐप आपकी हथेली पढ़ सकता है।',
  toolLink: (name: string) => `या ${name} में अपना आकार चुनें`,
  seeCard: 'यह प्रकार देखें',
  seeGuide: 'गाइड खोलें',
  seeSection: 'नीचे और पढ़ें',
  stepOf4: (n: number) => `4 में से कदम ${n}`,
  linesNav: '4 मुख्य रेखाएं',
  lineShort: { heart: 'हृदय रेखा', head: 'मस्तिष्क रेखा', life: 'जीवन रेखा', fate: 'भाग्य रेखा' },
  nextLine: (n: number) => `अगला: 4 में से कदम ${n}`,
  startLines: '4 मुख्य रेखाएं शुरू करें: 4 में से कदम 1',
  allFour: 'आपने चारों मुख्य रेखाएं देख लीं',
  allFourBody: 'हथेली की सभी रेखाओं का चार्ट छोटी रेखाएं भी दिखाता है।',
  doYouHave: 'क्या आपके हाथ में यह है?',
  booksSay: 'किताबें क्या कहती हैं',
  sourcesSummary: (n: number) => `स्रोत (${n})`,
  sourcesSummaryOf: (name: string, n: number) => `${name} गाइड के स्रोत (${n})`,
  tipChips: ['खुली हथेली', 'अच्छी रोशनी', 'पूरा हाथ फ़्रेम में'],
  tipCheckLink: 'पहले अपनी फ़ोटो जाँचें',
  photoShort: 'फ़ोन की फ़ोटो में मुख्य रेखाएं, उनकी टूट, शाखाएं और दो मुखी सिरे दिखते हैं। तारे और क्रॉस जैसे छोटे निशान बहुत छोटे होते हैं, इसलिए ईमानदार रीडिंग इन्हें छोड़ देती है।',
  // Guide v4 (WEB-DEC-047): placeholders for the Hindi reviewer. No Hindi guide uses them yet.
  teach: {
    heroAlt: (names: string) => `एक खुली दाईं हथेली की असली फ़ोटो, उंगलियां फैली हुई। असली PalmSays स्कैनर ने इस पर ये रेखाएं बनाईं: ${names}।`,
    heroCaption: 'हथेली की असली फ़ोटो (Hanna Pad, Pexels), जिस पर रेखाएं असली PalmSays स्कैनर ने बनाईं। आपकी रीडिंग आपकी अपनी फ़ोटो से बनती है।',
    leftPalmAlt: (lines: readonly string[]) =>
      `घर के अंदर ली गई एक असली खुली बाईं हथेली की फ़ोटो, जिस पर PalmSays ने ${lines.join(', ').replace(/, ([^,]*)$/, ' और $1')} रेखाएं ट्रेस कीं।`,
    leftPalmCaption: 'एक असली फ़ोटो, PalmSays से ट्रेस की गई। आपकी रीडिंग आपकी अपनी फ़ोटो से बनती है।',
    showLine: 'एक रेखा देखें',
    allLines: 'सभी',
    notClear: 'इस फ़ोटो में साफ़ नहीं दिखी',
    playAgain: 'फिर से चलाएं',
    fingers: ['अंगूठा', 'तर्जनी', 'मध्यमा', 'अनामिका', 'कनिष्ठा'],
    drawing: 'चित्र',
    aiImage: 'AI चित्र',
    wordsCredit: 'ये तस्वीरें AI से बनी 3D छवियां हैं।',
    wordsTitle: 'हस्तरेखा के ज़रूरी शब्द',
    words: [
      { key: 'line', term: 'रेखा', hi: 'रेखा', hiLatin: 'rekha', text: 'हथेली पर एक लंबी सिलवट। हस्तरेखा चार मुख्य रेखाएं पढ़ती है।' },
      { key: 'crease', term: 'सिलवट', hi: 'सिलवट', hiLatin: 'silvat', text: 'त्वचा का एक मोड़। उंगलियों की जड़ में छोटी सिलवटें उंगलियों की होती हैं।' },
      { key: 'mount', term: 'पर्वत', hi: 'पर्वत', hiLatin: 'parvat', text: 'हथेली का नरम, उभरा हिस्सा, जैसे अंगूठे की जड़ का उभार।' },
      { key: 'fork', term: 'दो मुखी रेखा', hi: 'दो मुखी रेखा', hiLatin: 'do mukhi rekha', text: 'एक सिरे पर दो में बंटती रेखा।' },
      { key: 'break', term: 'टूट', hi: 'टूट', hiLatin: 'toot', text: 'जहां रेखा रुककर फिर शुरू होती है।' },
      { key: 'hand', term: 'लिखने वाला हाथ', hi: 'लिखने वाला हाथ', hiLatin: 'likhne wala haath', text: 'जिस हाथ से आप लिखते हैं। परंपरा इसे वह जीवन मानती है जो आप बना रहे हैं।' },
    ],
    flowTitle: 'रीडिंग कैसे होती है',
    flow: [
      { title: 'देखें', text: 'रेखाएं, पर्वत और हाथ का आकार।' },
      { title: 'जानें', text: 'पुरानी किताबें हर एक के बारे में क्या कहती हैं।' },
      { title: 'खुद से पूछें', text: '“क्या यह मुझ पर लागू होता है?”' },
    ],
    stepMapTitle: '7 कदम एक नज़र में',
    doLabel: 'ऐसे',
    dontLabel: 'ऐसे नहीं',
    photoDo: { alt: 'हल्की, एक-सी रोशनी में सीधी खुली हथेली, पूरा हाथ कैमरे के पास।', text: 'खुली हथेली, दिन की रोशनी, पास से।' },
    photoDonts: [
      { key: 'dark', alt: 'अंधेरे कमरे में उठा हुआ हाथ, ज़्यादातर परछाईं में।', text: 'बहुत अंधेरा। दिन की रोशनी लें।' },
      { key: 'fist', alt: 'बंद मुट्ठी।', text: 'बंद हाथ। हथेली खोलें।' },
      { key: 'far', alt: 'लंबे गलियारे के आख़िर में हाथ उठाए एक व्यक्ति, इतना दूर कि रेखाएं नहीं दिखतीं।', text: 'बहुत दूर। फ़्रेम भरें।' },
      { key: 'back', alt: 'हाथ का पिछला हिस्सा, उंगलियां फैली हुई।', text: 'हाथ का पिछला हिस्सा। हथेली दिखाएं।' },
    ],
    photoCaption: 'सही फ़ोटो असली है (Hanna Pad, Pexels); बाकी उदाहरण फ़ोटो AI से बनी हैं। अंधेरी फ़ोटो में परछाईं अतिरिक्त रेखा या टूट जैसी दिख सकती है।',
    hands: {
      writing: 'आपका लिखने वाला हाथ',
      writingText: 'जो जीवन आप बना रहे हैं',
      other: 'आपका दूसरा हाथ',
      otherText: 'जिसके साथ आपने शुरुआत की',
      writingAlt: 'कलम से कागज़ पर लिखता हुआ हाथ।',
      otherAlt: 'दूसरा हाथ, हथेली ऊपर, आराम से खुला।',
      caption: 'परंपरा दोनों हाथों को अलग पढ़ती है, इसलिए दोनों देखें।',
    },
    shapesCaption: 'कीरो की Palmistry for All (1916) के सात हाथ-प्रकारों की AI से बनी 3D तस्वीरें। असली लोगों के हाथ नहीं।',
    shapes: {
      elementary: { name: 'प्रारंभिक', alt: 'छोटी, मोटी हथेली और छोटी उंगलियां' },
      square: { name: 'चौकोर', alt: 'चौकोर हथेली, सीधी कटी उंगलियां' },
      spatulate: { name: 'चमसाकार', alt: 'सिरों पर चौड़ी होती उंगलियां' },
      philosophic: { name: 'दार्शनिक', alt: 'गांठदार जोड़ों वाला लंबा हाथ' },
      conic: { name: 'शंक्वाकार', alt: 'गोल, पतली होती उंगलियों वाला हाथ' },
      psychic: { name: 'आदर्शवादी', alt: 'पतली, नुकीली उंगलियों वाला लंबा, संकरा हाथ' },
      mixed: { name: 'मिश्रित', alt: 'हर उंगली का अलग आकार' },
    },
    readFor: 'किसके लिए पढ़ें',
    readForLine: {
      heart: 'आप कैसा महसूस करते हैं और प्यार कैसे दिखाते हैं।',
      head: 'आप कैसे सोचते और फ़ैसले लेते हैं।',
      life: 'ऊर्जा और बदलाव से आप कैसे निपटते हैं। उम्र के लिए कभी नहीं।',
      fate: 'दिशा और काम। कई हथेलियों में यह हल्की होती है या होती ही नहीं।',
    },
    lessonAlt: {
      heart: 'असली हथेली का पास का दृश्य। स्कैनर की हृदय रेखा कनिष्ठा की तरफ़ से तर्जनी और मध्यमा के बीच तक जाती है।',
      head: 'असली हथेली का पास का दृश्य। स्कैनर की मस्तिष्क रेखा अंगूठे और तर्जनी के बीच से शुरू होकर हथेली के बीच से जाती है।',
      life: 'असली हथेली का पास का दृश्य। स्कैनर की जीवन रेखा अंगूठे और तर्जनी के बीच से शुरू होकर अंगूठे के उभार के चारों ओर मुड़ती है।',
      fate: 'असली हथेली का पास का दृश्य। स्कैनर की भाग्य रेखा हथेली के बीच से सीधे मध्यमा की ओर जाती है।',
    },
    lessonCaption: (line: string) => `फ़ोटो: उसी असली हथेली पर ${line}, स्कैनर से बनी। चित्र: किताबों में बताए तीन रूप, असली हथेलियां नहीं।`,
    formsTitle: 'देखने लायक तीन रूप',
    openGuide: (line: string) => `${line} का अर्थ`,
    questionsTitle: '4 रेखाएं, 4 सवाल',
    questions: {
      heart: 'मैं कैसा महसूस करता हूं, और उसे कैसे दिखाता हूं?',
      head: 'मैं कैसे सोचता और फ़ैसले लेता हूं?',
      life: 'मैं अपनी ऊर्जा कैसे लगाता हूं और बदलाव से कैसे निपटता हूं?',
      fate: 'मेरा काम किस दिशा में जा रहा है?',
    },
    mountsAlt: 'असली हथेली पर आठ गिने हुए हिस्से: चार उंगलियों के नीचे, एक अंगूठे के पास जीवन रेखा की शुरुआत के अंदर, अंगूठे का उभार, और दो बाहरी किनारे पर कलाई के ऊपर।',
    mountsCaption: 'पर्वतों के हिस्से स्कैनर के हाथ-बिंदुओं (उंगलियों की जड़, अंगूठा, कलाई) से वहां रखे गए हैं जहां किताबें बताती हैं। ये हिस्से हैं, रेखाएं नहीं।',
    mounts: {
      jupiter: { name: 'गुरु', hi: 'गुरु', planet: 'बृहस्पति', where: 'तर्जनी के नीचे' },
      saturn: { name: 'शनि', hi: 'शनि', planet: 'शनि', where: 'मध्यमा के नीचे' },
      sun: { name: 'सूर्य', hi: 'सूर्य', planet: 'सूर्य', where: 'अनामिका के नीचे' },
      mercury: { name: 'बुध', hi: 'बुध', planet: 'बुध', where: 'कनिष्ठा के नीचे' },
      venus: { name: 'शुक्र', hi: 'शुक्र', planet: 'शुक्र', where: 'अंगूठे का उभार' },
      moon: { name: 'चंद्र', hi: 'चंद्र', planet: 'चंद्र', where: 'बाहरी किनारा, कलाई के ऊपर' },
      marsInner: { name: 'मंगल', hi: 'मंगल', planet: 'मंगल', where: 'अंगूठे के पास' },
      marsOuter: { name: 'मंगल', hi: 'मंगल', planet: 'मंगल', where: 'बाहरी किनारा' },
    },
    notThis: 'यह नहीं',
    this: 'यह',
    mistakes: {
      crease: {
        not: 'जहां उंगलियां हथेली से मिलती हैं, वहां की छोटी सिलवटें उंगलियों की होती हैं।',
        notAlt: 'असली हथेली पर उंगलियों की जड़, उंगलियों की सिलवटें एक हिस्से के रूप में दिखाई गई हैं।',
        yes: 'हृदय रेखा उनके नीचे की पहली लंबी रेखा है।',
        yesAlt: 'वही दृश्य, उंगलियों की सिलवटों के नीचे स्कैनर की हृदय रेखा।',
      },
      start: {
        not: 'जो रेखा अंगूठे के पास से शुरू होती है, वह मस्तिष्क रेखा है।',
        notAlt: 'असली हथेली पर स्कैनर की मस्तिष्क रेखा, अंगूठे के पास उसकी शुरुआत दिखाई गई है।',
        yes: 'हृदय रेखा कनिष्ठा वाले किनारे से शुरू होती है।',
        yesAlt: 'असली हथेली पर स्कैनर की हृदय रेखा, कनिष्ठा वाले किनारे पर उसकी शुरुआत दिखाई गई है।',
      },
      shadow: {
        not: 'अंधेरी फ़ोटो। परछाईं टूट जैसी दिख सकती है।',
        notAlt: 'अंधेरे कमरे में ली गई हाथ की फ़ोटो, ज़्यादातर परछाईं में।',
        yes: 'दिन की बराबर रोशनी। जीवन रेखा एक रेखा दिखती है।',
        yesAlt: 'दिन की रोशनी में असली हथेली, स्कैनर की जीवन रेखा बिना टूट के।',
      },
    },
    right: 'हां, सही है।',
    wrong: 'पूरी तरह नहीं।',
    quizCropAlt: 'असली हथेली का पास का दृश्य, स्कैनर की एक रेखा सुनहरे रंग में।',
    quiz: [
      {
        q: 'इस फ़ोटो पर सुनहरे रंग में कौन सी रेखा है?',
        crop: 'life',
        options: [
          { text: 'हृदय रेखा', ok: false, fb: 'हृदय रेखा सबसे ऊपर, उंगलियों के ठीक नीचे होती है।' },
          { text: 'मस्तिष्क रेखा', ok: false, fb: 'क़रीब। मस्तिष्क रेखा यहीं से शुरू होकर हथेली के आर-पार जाती है।' },
          { text: 'जीवन रेखा', ok: true, fb: 'यह अंगूठे के उभार के चारों ओर कलाई की तरफ़ मुड़ती है।' },
        ],
      },
      {
        q: 'हृदय रेखा कहां से शुरू होती है?',
        crop: null,
        options: [
          { text: 'हथेली के कनिष्ठा वाले किनारे से', ok: true, fb: 'वहां से यह तर्जनी या मध्यमा की ओर जाती है।' },
          { text: 'अंगूठे और तर्जनी के बीच से', ok: false, fb: 'वहां से मस्तिष्क और जीवन रेखा शुरू होती हैं।' },
          { text: 'कलाई से', ok: false, fb: 'भाग्य रेखा कलाई से शुरू हो सकती है। हृदय रेखा कनिष्ठा वाले किनारे से।' },
        ],
      },
      {
        q: 'जीवन रेखा की लंबाई आपकी उम्र के बारे में क्या बताती है?',
        crop: null,
        options: [
          { text: 'छोटी रेखा मतलब छोटी उम्र', ok: false, fb: 'नहीं। लंबाई से उम्र नहीं आंकी जाती, और फ़ोटो में रेखा छोटी दिख सकती है।' },
          { text: 'कुछ नहीं: लंबाई से उम्र नहीं आंकी जाती', ok: true, fb: 'किताबें जीवन रेखा को ऊर्जा और बदलाव से जोड़ती हैं।' },
          { text: 'बड़ा बदलाव किस साल आएगा', ok: false, fb: 'कोई रेखा तारीख़ नहीं बताती। हस्तरेखा झुकाव बताती है।' },
        ],
      },
    ],
    quizMore: 'और अभ्यास: हस्तरेखा क्विज़',
    // The 4 line guides (v4 rollout): English placeholders until the Hindi reviewer writes them.
    // No Hindi line guide is built yet (CONTENT_GUIDE.md §10), so these never show.
    focusAlt: en.teach.focusAlt,
    focusNote: en.teach.focusNote,
    start: 'शुरू',
    end: 'अंत',
    skipThese: en.teach.skipThese,
    looksTitle: en.teach.looksTitle,
    looks: en.teach.looks,
    looksAlt: en.teach.looksAlt,
    looksCaption: en.teach.looksCaption,
    anatomyTitle: en.teach.anatomyTitle,
    anatomy: en.teach.anatomy,
    anatomyHint: en.teach.anatomyHint,
    anatomyCaption: en.teach.anatomyCaption,
    sideBySide: en.teach.sideBySide,
    drawingsCaption: en.teach.drawingsCaption,
    flowChoice: en.teach.flowChoice,
    flowChoiceLF: en.teach.flowChoiceLF,
    heartEnds: en.teach.heartEnds,
    lineQuiz: en.teach.lineQuiz,
  },
};

const strings: Record<Locale, GuideStrings> = { en, hi };

export function guideStrings(locale: Locale): GuideStrings {
  return strings[locale];
}
